### ISSUE TITLE
Menu quickly closes on attempting to open after changing dimensions.

### ISSUE THREAD

**Issue by sSomename** [Ketheroth/Slots#1]
### Issue
Opening menu will work fine but after moving to a new dimension vanilla or modded it will flash on screen for a moment and disappear and continue this behavior until the player dies.

### Server Modlist

- 1.18.1-enchantedgoldenapplecrafting-1.0.jar 
- [1.18.1]-Epic-Knights-Armor-and-Weapons-5.8v.jar 
- [Forge]+Wildfire+Female+Gender+Mod-2.8.1.jar 
- advancedperipherals-1.18.1-0.7.11b.jar 
- anvilrestoration_1.18.1-1.2.jar 
- Aquaculture-1.18.1-2.3.3.jar 
- aquatictorches-1.18-1.1.0.jar 
- architectury-3.7.22.jar 
- balm-2.4.2+0.jar 
- bedspreads-forge-1.18.1-5.1.0.5.jar 
- Beyond-Earth-1.18.1-6.0d.jar 
- blue_skies-1.18.1-1.3.3.jar 
- blueprint-1.18.1-5.1.1.jar 
- bmorph-1.18.1-2.0.1.jar 
- bowyery-0.8b.jar 
- brass_armory-1.18.1-1.5-alpha.jar 
- carryon-1.18.1-1.17.0.7.jar 
- castle_in_the_sky-1.18.1-0.4.0.jar 
- cc-tweaked-1.18.1-1.100.2.jar 
- charginggadgets-1.6.0.jar 
- chipped-1.18.1-1.2.1-forge.jar 
- ChiselsBits-forge-1.18.1-1.2.81-universal.jar 
- Chunky-1.2.164.jar 
- citadel-1.10.10-1.18.jar 
- ClaimChunk-1.18-1.0.0.12.jar 
- collective-1.18.1-4.0.jar 
- collective-1.18.1-4.7.jar 
- compactmachines-4.0.0-beta.4.jar 
- configured-1.5.3-1.18.1.jar 
- connectedglass-1.1.1-mc1.18.jar 
- constructionwand-1.18.1-2.6.jar 
- cookietology-1.18.1-1.1.0.jar 
- CopperEquipment-Forge1.18.1-1.2.jar 
- CosmeticArmorReworked-1.18.1-v1a.jar 
- cosmoslibrary-1.18.1-5.1.8.10-universal.jar 
- cosmosportals-1.18.1-3.1.5.80-universal.jar 
- Craftable+Horse+Armour++Saddle-1.18-1.8-Forge.jar 
- CraftingAutomat-MC1.18.1-1.2.3.jar 
- create-mc1.18.1_v0.4d.jar 
- createaddition-1.18.1-20220125a.jar 
- creeperoverhaul-1.18.1-0.3.0-forge.jar 
- crossbowverhaul-1.18.1-1.2.4-universal.jar 
- Cucumber-1.18.1-5.0.3.jar 
- curioofundying-forge-1.18-5.3.0.0.jar 
- curios-forge-1.18.1-5.0.6.0.jar 
- curious-armor-stands-1.18.1-4.0.0.jar 
- customizableelytra-1.18-1.6.3.jar 
- dcintegration-forge-2.3.5-1.18.jar 
- DiceMC+Money-1.18.1-2.0.14.jar 
- DoggyTalents-1.18.1-2.4.2.jar 
- drinkbeer-v2.3.5+for+1.18.1.jar 
- DungeonCrawl-1.18.1-2.3.7.jar 
- Dynmap-3.4-beta-1.1-forge-1.18.jar 
- EasyMagic-v3.2.1-1.18.1-Forge.jar 
- eatinganimation-1.18.1-2.0.1.jar 
- effective_for_forge-1.001.jar 
- Elemental-1.18.1-1.0.2.jar 
- elevatorid-1.18-1.8.3.jar 
- emojiful-1.18-3.0.0.jar 
- EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar 
- enchantwithmob-1.18.1-3.3.0.jar 
- endrem_forge-5.0.1-R-1.18.1.jar 
- enhancedcelestials-2.0.9-1.18.jar 
- ExtraArmor-1.18-1.13.3.jar 
- Fallingleaves-1.18.1-1.3.1.jar 
- feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.jar 
- ferritecore-4.1.1-forge.jar 
- fire_extinguisher_1.18.1-1.6.1.jar 
- flowingagony-1.18.1-1.2.3.jar 
- flywheel-forge-1.18-0.6.0.jar 
- FRV+Tools-2.1.jar 
- ftb-chunks-forge-1801.3.3-build.113.jar 
- ftb-library-forge-1801.3.5-build.109.jar 
- ftb-ranks-forge-1801.1.6-build.22.jar 
- ftb-teams-forge-1801.2.4-build.46.jar 
- furniture-7.0.0-pre28-1.18.1.jar 
- geckolib-1.18-forge-3.0.11.jar 
- globalxp-1.18.1-1.9.1.jar 
- goprone-1.18.1-1.6.0.jar 
- guardvillagers-1.18.1.4.0.jar 
- handoveryouritems_1.18.1-1.4.jar 
- hellfire-1.18.1-1.0.2.jar 
- humancompanions-1.18.1-1.3.0.jar 
- HyperLighting-1.18.1-1.2.1.jar 
- ImmersiveEngineering-1.18.1-7.1.0-145.jar 
- InsaneLib-1.4.3-mc1.18.1.jar 
- ironchest-1.18-13.0.7.jar 
- Jade-1.18-4.1.2.jar 
- jei-1.18.1-9.2.1.69.jar 
- journeymap-1.18.1-5.8.0beta15.jar 
- JustEnoughResources-1.18.1-0.13.1.138.jar 
- kleeslabs-forge-1.18.1-11.0.1.jar 
- kotlinforforge-3.1.0-obf.jar 
- LavaClearView-1.18-forge-3.0.1.jar 
- LeftHanging-forge-1.18.1-3.0.1.0.jar 
- lootr-1.18-0.1.14.48.jar 
- malum-1.18.1-1.2.2.jar 
- Mantle-1.18.1-1.8.31.jar 
- mcjtylib-1.18-6.0.9.jar 
- mcw-bridges-2.0.1-mc1.18.1.jar 
- mcw-doors-1.0.5-mc1.18.1.jar 
- mcw-roofs-2.1.0-mc1.18.1.jar 
- mcw-windows-2.0.2-mc1.18.1.jar 
- modnametooltip-1.18.1-1.18.0.jar 
- moreboots-3.0.1-1.18.x.jar 
- MoreVanillaArmor-1.18.1-3.0.0.jar 
- mutil-1.18.1-4.4.0.jar 
- MysticalAgradditions-1.18.1-5.0.2.jar 
- MysticalAgriculture-1.18.1-5.0.3.jar 
- MysticalCustomization-1.18.1-3.0.1.jar 
- neoncraft2-2.0.jar 
- no_null_processors_forge-2.0.2+1.18.1.jar 
- nomowanderer-1.18.1_1.0.jar 
- notenoughwands-1.18-4.0.0.jar 
- ObsidianBoat-1.2.1-build.10+mc1.18.1.jar 
- Paraglider-1.18-1.5.0.0.jar 
- Patchouli-1.18.1-65.jar 
- PatinaPipeworks-1.18.1-1.0.6-universal.jar 
- performant-1.18.1-5.1.jar 
- pipez-1.18.1-1.0.1.jar 
- pitg-1.18.1-2.0.2.jar 
- ProgressiveBosses-3.5.0-mc1.18.1.jar 
- PuzzlesLib-v3.1.5-1.18.1-Forge.jar 
- reap-1.18.1-1.0.1.jar 
- Redstone-Villager-1.18.1-1.0.jar 
- redstonepen-1.18.1-1.0.8.jar 
- relics-0.3.4.1.jar 
- repurposed_structures_forge-4.2.10+1.18.1.jar 
- sapience-1.18.1-1.0.2.jar 
- scuba_gear-1.18.1-1.0.4.jar 
- selene-1.18-1.12.0.jar 
- sit-1.18-1.3.1.jar 
- Slots-1.18.1-1.0.0.jar 
- Snad-1.18.1-1.21.12.11a.jar 
- snowyspirit-1.18-1.1.0.jar 
- sophisticatedbackpacks-1.18.1-3.15.1.505.jar 
- SoulHome-Mod-1.18.1-39.0.66-b1.jar 
- spellsword-1-18-1.jar 
- structure_gel-1.18.1-2.1.3.jar 
- swingthroughgrass-1.18.1-1.8.0.jar 
- TConstruct-1.18.1-3.4.1.46.jar 
- tetra-1.18.1-4.7.0.jar 
- the_bumblezone_forge-4.3.4+1.18.1.jar 
- time-in-a-bottle-2.1.0-mc1.18.1.jar 
- TonsOfEnchants-1.18.1-v1.0.jar 
- ToolBelt-1.18-1.18.0.jar 
- toolleveling-1.18-1.2.12.jar 
- torchmaster-18.0.3-beta.jar 
- trajans-tanks-forge-1.18-07.jar 
- TravelersBackpack-1.18.1-7.0.1.jar 
- Uppers-0.4.0.jar 
- Vampirism-1.18.1-1.8.0-beta.3.jar 
- veinmining-forge-1.18.1-0.17.jar 
- villagebellrecipe_1.18.1-1.4.jar 
- villagertools-1.18-1.0.2.jar 
- voicechat-forge-1.18.1-2.2.24.jar 
- voidtotem-forge-1.18.1-1.1.2.jar 
- walljump-forge-1.18.1-1.3.7.jar 
- witchesbrew-1.18.1-1.0.jar 
- wlrs-1.10.4.jar 
- worldedit-mod-7.2.9.jar 
- Xtra+Arrows+v1.7.1+MC1.18.jar 
- YungsApi-1.18.1-Forge-24.jar 
- fmlcore-1.18.1-39.0.76.jar 
- javafmllanguage-1.18.1-39.0.76.jar of 
- mclanguage-1.18.1-39.0.76.jar of type 
- server-1.18.1-20211210.034407-srg.jar 
- forge-1.18.1-39.0.76-universal.jar

**Comment by Ketheroth** [comment]
Thanks for reporting it
