### ISSUE TITLE
1.16.5/ 1.0.0 issue

### ISSUE THREAD

**Issue by Hir0shiyt** [Ketheroth/Slots#2]
Apparently when i go to the end and come back the items on the slots inventory dissapear

**Comment by Ketheroth** [comment]
thanks for letting me know, I forgot to fix it in 1.16 after fixing it in 1.18

**Comment by Ketheroth** [comment]
fixed in https://github.com/Ketheroth/Slots/commit/d639db7af2fc6ed9b45babfcc828ebaa2ca508ea
